inherits = 'catppuccin_mocha'
"ui.background" = { fg = "text" }
"ui.cursorline.primary" = { }

"ui.bufferline" = { fg = "#56586a" }
"ui.bufferline.active" = { fg = "mauve", bg = "base", underline = { color = "mauve", style = "line" } }
"ui.bufferline.background" = { }
